[package]
name = "ksql"
description = "A JSON data expression lexer, parser, cli and library"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-playground/ksql"
authors = ["Dean Karn <dean.karn@gmail.com>"]
keywords = [
    "json",
    "expression",
    "parser",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
#gjson = { version = "0.8.0" }
gjson = { version = "0.8.0", path = "../gjson.rs" }
thiserror = "1.0.30"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
